minimap:
  db: "/pbi/dept/appslab/datasets/dp_databases/mm_nt_db.mmi"
  threads: 24
  
sam2rma:
  path: "/home/dportik/programs/megan/tools/sam2rma"
  db: "/home/dportik/programs/megan/db/megan-nucl-map-Jul2020.db"
  threads: 24
  readassignmentmode: "readCount"
  # possible values = readCount, readLength, alignedBases, readMagnitude
