# The path to use as the temporary directory to write large files to, which is used with the
# --tmpdir flag in checkm, and the --scratch_dir flag in gtdb. If using HPC, use "/scratch" 
# if you have access. If you do not have access to "/scratch" on HPC or are running 
# snakemake locally, change to a valid directory.
tmpdir: "/scratch"


minimap:
  # The number of threads to use for minimap2.
  threads: 24
  
metabat:
  # The number of threads to use for metabat2.
  threads: 12
  
checkm:
  # The number of threads to use for checkm.
  threads: 24
  
  # The number of threads to use for pplacer when it is called within checkm.
  pplacer_threads: 12
  
  # A full path to the data downloaded from: https://data.ace.uq.edu.au/public/CheckM_databases/
  # The resulting file must be decompressed to use it.
  # This path is used for the "checkm data setRoot <checkm_data_dir>" command.
  # The path below must point to the directory that contains the following folders:
  # distributions, genome_tree, hmms, hmms_ssu, img, pfam, test_data, and the two tsv files.
  datapath: "/dept/appslab/datasets/dp_checkm/"
  
  
gtdbtk:
  # The minimum percent completeness for a genome bin.
  min_completeness: 70
  
  # The maximum percent contamination for a genome bin.
  max_contamination: 10
  
  # The maximum number of contigs allowed in a genome bin.
  max_contigs: 10
  
  # The number of threads to use for gtdbtk.
  threads: 32
  
  # The number of threads to use for pplacer when it is called within gtdbtk.
  pplacer_threads: 24
  
  # The path the database downloaded for gtdbtk.
  # For release 95, you can use:
  # wget https://data.ace.uq.edu.au/public/gtdb/data/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz
  # if the above link does not work, try this instead:
  # wget https://data.gtdb.ecogenomic.org/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz
  
  # Once downloaded, use: tar -xvzf gtdbtk_r95_data.tar.gz
  # Please note that these data are ~27GB in size.
  # The path below must point to the directory than contains the following folders:
  # fastani, markers, masks, metadata, mrca_red, msa, pplacer, radii, taxonomy
  gtdbtk_data: "/dept/appslab/datasets/dp_gtdb/release95/"
  
  # A label for the combined analysis of the samples included in a given run;
  # this is generally overriden by the Sample-Config.yaml.
  gtdb_full_label: "All"