rma2info:
  # The full path to the rma2info tool.
  # This tool is distributed as part of the MEGAN download, it is a binary.
  path: "/home/dportik/programs/megan/tools/rma2info"
    
  # Number of threads to use for rma2info. Set for memory usage of up to 5GB.
  threads: 12
  
# number of threads for final summary program, this may require up to 5GB memory.
summary_threads: 12