samplenames:
  # The sample names for the input RMA files. Please note that this name is a combination 
  # of the name provided here, and the "rma: fill: " argument below. With the current 
  # configuration, sample FP103 should correspond to a file labeled as 
  # FP103.nucleotide.readCount.rma in the inputs/ folder. 
  - "FP103"
  - "HL103"
  - "TD324"
    
# the location of the read counts text file, which should be in the inputs folder
readcounts: "inputs/Sample-Read-Counts.txt"

rma:
  # If there is additional text between the sample name and .rma extension, add it to this 
  # argument. For example, if the name is SR352.nucleotide.readCount.rma, you should use 
  # ".nucleotide.readCount". If the name is simply SR352.rma, you should enter a blank string 
  # below by using "" instead. The default from the Taxonomic-Profiling-Nucleotide 
  # pipeline is ".nucleotide.readCount".
  fill: ".nucleotide.readCount"
